### ISSUE TITLE
Could you please introduce the federated learning methods you used?

### ISSUE THREAD

**Issue by whdong-whu** [LIU-YUXI/FedFMS#1]
Thank you very much for your excellent work. Could you please introduce the federated learning methods you used? It would help better understand your code. Could I also have your contact information for further communication?

**Comment by LIU-YUXI** [comment]
Thank you for your interest in our work. The federated learning method we use is the most classic FedAvg, which is the method of weighted summation of parameters according to the data amount of each client. My email is liuyuxi.tongji@gmail.com, welcome to communicate！
